import ellie1 from "../../assets/img/Characters_img/ellie williams (1).jpg";
import ellie2 from "../../assets/img/Characters_img/Ellie Williams.jpg";

export const MainCharacters = [
  {
    id: 1,
    name: "Ellie Williams",
    image: ellie1,
    alt: "Ellie Williams",
    occupation: "Writer",
    bio: "Ellie Williams[5] is the central character of The Last of Us series.[fn 1] She serves as the protagonist of The Last of Us: American Dreams, the playable deuteragonist of The Last of Us Part I, the playable protagonist of The Last of Us: Left Behind, the playable dual protagonist of The Last of Us Part II,[1][6] and a playable character in the No Return mode Ellie grew up as an orphan in the Boston quarantine zone and attended a military preparatory school, where she met and befriended Riley Abel. When Ellie was fourteen, the pair were both infected with the Cordyceps brain infection, where Ellie discovered she was immune. A friend of her mothers and the leader of the Fireflies, Marlene, believed that she was the key to reverse engineering a vaccine. Marlene tasked Joel Miller, a smuggler, with escorting Ellie outside of the QZ. The simple drop-off turned into a year-long journey across America, and the two eventually formed a close bond Upon reaching the Fireflies in Salt Lake City, Joel learned that only killing Ellie could create the cure. Refusing to allow this, he killed the head surgeon and escaped with Ellie to settle down in Jackson, his brothers community in Wyoming. For the next four years, Ellie came to resent Joel for saving her life. In 2038, Abby Anderson, a former Firefly and the surgeons daughter, found and killed Joel. Ellie vowed revenge and pursued Abby to Seattle. Her efforts were fruitless, leading her to retire on a farm with her girlfriend Dina and her son JJ. Unable to forgive Abby, Ellie abandoned her family and pursued her once again to Santa Barbara, only to spare Abby in the end. She returned to the farm once more, coming to terms with Joels death and his decision to save her life.",
    Biographical: {
      other_names: [
        "Kiddo (by Joel)",
        "Baby girl (by Joel)",
        "Little Rabbit (by David)",
        "New Kid (by Riley)",
        "Brick Master (by herself)",
        "Herding Master (by herself)",
        "El (by Dina)",
        "Babe (by Dina)",
      ],
      birthdate: "2019",
      age: 19,
      status: "Alive",
      gender: "Female",
      Occupataion: "Military School Cadet",
      Relationsip: [
        "Anna (mother)",
        "Cat (ex-girlfriend)",
        "Dina (ex-girlfriend)",
        "JJ (adopted son)",
        "Joel Miller (surrogate father)",
      ],
      HairColor: "Aubrun",
      EyeColor: "Green",
    },
  },
  {
    id: 2,
    name: "Abby Anderson",
    image: ellie2,
    alt: "Abby Anderson",
    bio: "Abigail Abby Anderson is the playable dual protagonist of The Last of Us Part II[7][8] and a playable character in the No Return mode.[9] A member of the Fireflies broken by tragedy when Joel Miller killed her father Jerry Anderson, Abby made it her mission to avenge Jerry's demise.[10] However, it is only after her vengeance that she embarks on a journey with companion Lev and rediscovers purpose in her life.[6]",
    Biographical: {
      other_names: [
        "Abs (by Jerry and Manny)",
        "Wolf (by Seraphites)",
        "Traitor (by WLF)",
      ],
      birthdate: ". 2014–2018",
      age: "Early 20s[1]",
      status: "Alive",
      gender: "Female",
      Occupataion: "",

      Relationsip: ["Jerry Anderson (father)", "Owen Moore (ex-boyfriend)"],
      HairColor: "Dirty blonde[2]",
      EyeColor: "Blue[3]",
    },
  },
  {
    id: 3,
    name: "Joel Miler",
    image: ellie2,
    alt: "joel miler",
    bio: "Joel Miller is the playable protagonist of The Last of Us Part I, a supporting character in The Last of Us: Left Behind and The Last of Us Part II, the latter of which he is briefly playable in, and a playable character in the No Return mode.[4]Joel was a survivor in post-apocalyptic America that had been ravaged by the Cordyceps brain infection.[5] After losing his only daughter Sarah in the early stages of the outbreak,[6] Joel became a ruthless and cynical smuggler eventually tasked with smuggling and protecting Ellie Williams, a young girl who was the key to mankind's survival.[7] Joel eventually formed a strong bond with her.[8]",
    Biographical: {
      other_names: ["Texas (by Tess)", "Old timer (by Henry)"],
      birthdate: "September 26, 1981",
      age: "56 (Part II)",
      status: "Deceased",
      gender: "Male",
      Occupataion: [
        "Carpenter (formerly)",
        "Smuggler (formerly)",
        "Jackson patrolman",
      ],
      Relationsip: [
        "Tommy Miller (younger brother)",
        "Maria Miller (sister-in-law",
        "Unnamed ex-wife",
        "Sarah Miller (daughter)",
        "Ellie Williams (surrogate daughter)",
      ],
      HairColor: "Black (graying)",
      EyeColor: "Hazel",
    },
  },

  {
    id: 4,
    name: "Dina",
    image: ellie2,
    alt: "Dina",
    bio: "Dina is the deuteragonist of Ellie's story in The Last of Us Part II and a playable character in the No Return mode.[3] She is Ellie's partner and assists her in her quest for revenge.[4]",
    Biographical: {
      other_names: "Babe (by Ellie)",
      birthdate: "2015-2018",
      age: "20-23",
      status: "Alive",
      gender: "Female",
      Occupataion: ["Jackson patrolman (formerly)", "Farmer (formerly)"],
      Relationsip: [
        "JJ (son)",
        "Ellie Williams (ex-girlfriend)",
        "Jesse (ex-boyfriend)",
        "Unnamed mother",
        "Talia (older sister)",
      ],
      HairColor: "Black",
      EyeColor: "Brown",
    },
  },
  {
    id: 5,
    name: "Tommy Miller",
    image: ellie2,
    alt: "Tommy Miller",
    bio: "Tommy Miller is a supporting character in The Last of Us Part I and The Last of Us Part II, and a playable character in the No Return mode.[2] He is Joel's younger brother, and Sarah's paternal uncle.A caring and compassionate man, Tommy survived the early years of the outbreak with Joel.[3] However, the two separated as Tommy sought a more meaningful life than mere survival, leading him to join the Fireflies and later seek redemption through his wife, Maria, and the community of Jackson.[4]",
    Biographical: {
      other_names: [
        "Little brother (by Joel)",
        "Baby brother (by Joel)",
        "Uncle Tommy (by Sarah)",
      ],
      birthdate: "N/A",
      age: "N/A",
      status: "Alive",
      gender: "Male",
      Occupataion: [
        "Carpenter (formerly)",
        "Insurgent (formerly)",
        "Jackson patrolman",
      ],
      Relationsip: [
        "Maria Miller (wife)",
        "Joel Miller (older brother)",
        "Sarah Miller (niece)",
        "Unnamed mother",
      ],
      HairColor: "Dirty blond",
      EyeColor: "Green",
    },
  },
];
